# Generated by Django 2.0.4 on 2018-07-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuestionario', '0001_initial'),
        ('Curso', '0001_initial'),
        ('CuestionarioGeneral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasCuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RespuestaEstudiante', models.BooleanField()),
                ('CodigoCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.Cuestionario')),
                ('CodigoCuestionarioGeneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CuestionarioGeneral.CuestionarioGeneral')),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
            ],
        ),
    ]
