# Generated by Django 2.0.5 on 2018-05-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=300)),
                ('Curso', models.CharField(max_length=30)),
                ('Contrasena', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
            ],
        ),
    ]
