# Generated by Django 2.0.4 on 2018-06-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('CantidadEstudiantes', models.IntegerField()),
            ],
        ),
    ]
