# Generated by Django 2.0.4 on 2018-07-13 20:07

import Apps.Cuestionario.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '0001_initial'),
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enunciado', models.CharField(max_length=250, unique=True, validators=[Apps.Cuestionario.models.titulo_validation])),
                ('Respuesta', models.BooleanField()),
                ('CodigoTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema.Tema')),
                ('idProfesor', models.ForeignKey(default=2751234, on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor')),
            ],
        ),
    ]
