# Generated by Django 2.0.4 on 2018-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('celular', models.IntegerField()),
                ('cantidadHijos', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
