# Generated by Django 2.0.4 on 2018-07-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('CodigoTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema.Tema')),
            ],
        ),
    ]
