# Generated by Django 2.0.5 on 2018-05-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Curso', '0001_initial'),
        ('Profesor', '0001_initial'),
        ('Tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Estado_Actividad', models.CharField(max_length=30)),
                ('Fecha_Creacion', models.DateField()),
                ('Descripcion', models.CharField(max_length=30)),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor')),
                ('idTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema.Tema')),
                ('filename', models.CharField(max_length=100)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('Fecha_Entrega', models.DateField()),
                ('idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                
            ],
        ),
    ]
