# Generated by Django 2.0.4 on 2018-06-24 01:03

import Apps.Actividad.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tema', '0001_initial'),
        ('Curso', '0001_initial'),
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, unique=True, validators=[Apps.Actividad.models.titulo_validation])),
                ('Fecha_Creacion', models.DateField(auto_now_add=True)),
                ('Descripcion', models.CharField(max_length=30, validators=[Apps.Actividad.models.titulo_validation])),
                ('docfile', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
                ('Fecha_Entrega', models.DateField(verbose_name='validators=[validarFecha]')),
                ('idCurso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('idProfesor', models.ForeignKey(default=2751234, on_delete=django.db.models.deletion.CASCADE, to='Profesor.Profesor')),
                ('idTema', models.ForeignKey(default=555, on_delete=django.db.models.deletion.CASCADE, to='Tema.Tema')),
            ],
        ),
    ]
